/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

plugins {
    java
    application
    id("com.google.cloud.tools.jib") version "1.1.2"
}

jib {
    from.image = "amazoncorretto:11"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.amazonaws:aws-java-sdk-s3:1.11.683")
    implementation("com.amazonaws:aws-java-sdk-sts:1.11.683")
}

application {
    mainClassName = "aws.example.s3.App"
}
